sudo: false

language: php

php:
    - 7.1
    - 7.2

notifications:
email: false

before_script:
    - composer install --no-interaction

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs --standard=PSR2 src/
