sudo: false

language: php

php:
    - 7.1
    - 7.2

notifications:
email: false

before_script:
    - composer install --no-interaction

script:
    - $COMPOSER_BIN_DIR/phpunit
    - $COMPOSER_BIN_DIR/phpcs --standard=PSR2 src/
